### ISSUE TITLE
Add node app_id for using this pkg with sway

### ISSUE THREAD

**Issue by quite** [i3/go-i3#14]
I'm using this pkg for supporting both i3 and sway in my https://github.com/quite/i3gopher 

I just found out that I'd need to get hold of the `app_id` of a node, which is only available under sway (approx like the window instance in X11). I'm using this pkg because it is so good, and I did from the beginning only support i3. And thanks to https://github.com/i3/go-i3/issues/4 it just works out of the box with sway. Only now did I run into the missing app_id for i3gopher's exclude functionality.

Having read the #4 issue I'm thinking that you might be wary of making such a sway-specific addition to this pkg @stapelberg . What do you think? I have not come across the fork of this pkg that @dlasky mentioned, which blanked-renames it to go-sway. But I also think that is not such a great idea.

**Comment by dlasky** [comment]
you may want to check out github.com/joshuarubin/go-sway, i've been using it rather than this package for some sway specific stuff in the bar i'm slowly working on.

**Comment by stapelberg** [comment]
As long as any additions don’t clash with i3 (conflicting names or types), I think it’s fine to add them to this package.

That said, the package is largely stable, so if anyone wants to maintain a fork, that’s also a possibility.

Ideally for the mid- to long-term, though, I think there should ideally be just one Go package that everyone uses to communicate with i3 and/or sway, not a fractured landscape of multiple concurrently active repositories.

**Comment by quite** [comment]
I sounds like this small patch can be accepted! I'm happy to continue using go-i3 with both i3 and Sway, and to contribute to support that. Please see https://github.com/i3/go-i3/pull/15
