### ISSUE TITLE
Interest check -- sway support?

### ISSUE THREAD

**Issue by dlasky** [i3/go-i3#4]
It looks like only https://github.com/i3/go-i3/blob/master/socket.go#L32 would need to be abstracted to an environment var with a sane default to i3 if you wanted to support [swaywm](https://github.com/swaywm/sway). 

More than happy to PR this if there is any interest.

**Comment by stapelberg** [comment]
I’m torn about this. On the one hand, if adding support is easy, I don’t want to stand in the way. On the other hand, I’m not testing this library with sway, and I don’t want to give users the wrong impression.

Is it common to use i3 ipc libraries with sway in other languages?

Perhaps we could make the socket path customizable in a way that conveys to users that they are now leaving tested territory.

**Comment by dlasky** [comment]
I knew that would be a dilemma which is why I wanted to ask before I did any work on it.

I really cant speak for how common it is. Someone already forked it and just did a blanket rename to sway, which I think is the wrong approach because then they don't benefit from any upstream changes. Personally i'm interested in replacing my homerolled implementation of the IPC with this for a simple wallpaper app i've been working on.

This was what I came up with last night playing around with it: https://github.com/dlasky/go-i3/blob/master/socket.go#L27-L40

I think if we wanted to make it clear it was unsupported I might change that approach to something along the lines of `env UNSUPPORTED_SOCKET_CMD=sway ./binary` or maybe stdio something to that effect as well?

**Comment by stapelberg** [comment]
> Someone already forked it and just did a blanket rename to sway, which I think is the wrong approach because then they don't benefit from any upstream changes.

Ugh, agreed :). We should try getting that fork removed once we figured out this issue.

> I think if we wanted to make it clear it was unsupported I might change that approach to something along the lines of `env UNSUPPORTED_SOCKET_CMD=sway ./binary` or maybe stdio something to that effect as well?

I think we could introduce a hook for getting the socket path, something like `var SocketPathHook = func() string`, so that you can use whichever logic (e.g. hard-coded to a function which queries sway, environment variables, flags, …) you deem appropriate. We should add a note to the documentation of that hook that clarifies that the package is only tested with i3 itself.

Does that make sense?

**Comment by dlasky** [comment]
It does i think--user would override that singleton to implement?

Apologies for the delay i was grepping through the codebase looking at how hard it would be to implement something like a `WithSocket()` style pattern which felt a bit less dirty to me than overriding a var like that:

`i3instance := i3.New()` vs `i3instance := i3.NewWithSocketFactory(func getSocket() net.Conn {})`

but i think the two different setups for roundtrip and subscribe prevent this from being super clean as without that base instance there would have to be a ton of additional override with methods for the various entry points.

**Comment by stapelberg** [comment]
> It does i think--user would override that singleton to implement?

Yep.

> Apologies for the delay i was grepping through the codebase looking at how hard it would be to implement something like a `WithSocket()` style pattern which felt a bit less dirty to me than overriding a var like that:
> 
> `i3instance := i3.New()` vs `i3instance := i3.NewWithSocketFactory(func getSocket() net.Conn {})`

The mental model of this package is that there is one i3 instance with which one interacts (which is *by far* the most common scenario), so a package-level hook is appropriate.

> starting to think this is touching too many parts of your code for something that wouldn't be supported.

Does sway have a way to check if it’s running? Two hooks would still be okay with me.

**Comment by dlasky** [comment]
I'm not aware of one if it exists. I'm not sure sway has quite the same problem since you don't have to be running XServer so pgrep probably suffices.

**Comment by stapelberg** [comment]
With PR #5 merged, you should now be able to use the package to talk to sway.
