### ISSUE TITLE
Don't log variant detection

### ISSUE THREAD

**Issue by quite** [i3/go-i3#9]
It would be nice if the api did not log the detection of the version Variant. Is there a need to communicate that this is unsupported?

I'm writing a small tool with I'd like to be usable both with i3 and sway. https://github.com/quite/i3gopher

Though the tool is supposed to be run in the background, this frequently logged string (on every messaged roundtripped!) will drown any other relevant logging (error or otherwise) that it does.

I see that we can't really return non-nil since that'd stop the variant from being accepted. What to do...

@dlasky what do you think?

**Comment by stapelberg** [comment]
We should print the message just once per program, not on every round-tripped message.

**Comment by dlasky** [comment]
You want me to address?

**Comment by stapelberg** [comment]
If you have the time, sure, please send a PR.

**Comment by dlasky** [comment]
pretty simple
